pip install accelerate
pip install aiohttp
pip install aiosignal
pip install annotated-types
pip install appdirs
pip install asttokens
pip install async-timeout
pip install attrs
pip install bitsandbytes
pip install brotli
pip install certifi
pip install charset-normalizer
pip install click
pip install comm
pip install datasets
pip install debugpy
pip install decorator
pip install decord
pip install deepspeed
pip install dill
pip install dnspython
pip install docker-pycreds
pip install docstring-parser
pip install einops
pip install entrypoints
pip install exceptiongroup
pip install executing
pip install filelock
pip install frozenlist
pip install fsspec
pip install ftfy
pip install gitdb
pip install gitpython
pip install gmpy2
pip install hjson
pip install huggingface-hub
pip install idna
pip install intel-openmp
pip install ipykernel
pip install ipython
pip install ipywidgets
pip install jedi
pip install jinja2
pip install jupyter-client
pip install jupyter-core
pip install jupyterlab-widgets
pip install liger-kernel
pip install markdown-it-py
pip install markupsafe
pip install matplotlib-inline
pip install mdurl
pip install mkl
pip install mkl-fft
pip install mkl-random
pip install mkl-service
pip install mpmath
pip install msgpack
pip install multidict
pip install multiprocess
pip install nest-asyncio
pip install networkx
pip install ninja
pip install numpy
pip install nvidia-cublas-cu12
pip install nvidia-cuda-cupti-cu12
pip install nvidia-cuda-nvrtc-cu12
pip install nvidia-cuda-runtime-cu12
pip install nvidia-cudnn-cu12
pip install nvidia-cufft-cu12
pip install nvidia-curand-cu12
pip install nvidia-cusolver-cu12
pip install nvidia-cusparse-cu12
pip install nvidia-ml-py
pip install nvidia-nccl-cu12
pip install nvidia-nvjitlink-cu12
pip install nvidia-nvtx-cu12
pip install packaging
pip install pandas
pip install parso
pip install peft
pip install pexpect
pip install pickleshare
pip install pillow
pip install platformdirs
pip install prompt-toolkit
pip install protobuf
pip install psutil
pip install ptyprocess
pip install pure-eval
pip install py-cpuinfo
pip install pyarrow
pip install pyarrow-hotfix
pip install pydantic
pip install pydantic-core
pip install pygments
pip install pynvml
pip install pysocks
pip install python-dateutil
pip install pytz
pip install pyyaml
pip install pyzmq
pip install regex
pip install requests
pip install rich
pip install safetensors
pip install sentencepiece
pip install sentry-sdk
pip install setproctitle
pip install shtab
pip install six
pip install smmap
pip install stack-data
pip install sympy
pip install tbb
pip install tensorboardx
pip install tokenizers
pip install torch
pip install torchao
pip install torchaudio
pip install torchvision
pip install tornado
pip install tqdm
pip install traitlets
pip install transformers
pip install triton
pip install trl
pip install typing-extensions
pip install tyro
pip install tzdata
pip install ujson
pip install urllib3
pip install wandb
pip install wcwidth
pip install widgetsnbextension
pip install xxhash
pip install yarl
